name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: python scripts/format.py
      - run: git diff --exit-code

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bazelbuild/setup-bazelisk@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: make prepare-ci
      - run: make all
      - run: bazel build //:eclipse_update_site

